name: 'Wolkezeug'
description: 'Deploy managed resources to AWS via manifest'
branding:
  icon: cloud-snow
  color: blue
inputs:
  deploy-env:  
    description: 'envt for overrides'
    required: true
    default: 'nonprod'
  aws-region:  
    description: 'region'
    required: true
    default: 'us-east-1'
  timeout:  
    description: 'wait for service stability'
    required: true
    default: '5'
  artifact:  
    description: 'artifact name'
    required: false
  version:  
    description: 'wait for service stability'
    required: false
  path:  
    description: 'file loc'
    required: false
    default: '/'
runs:
  using: 'docker'
  image: 'docker://lonewolfworks/wolkezeug:BETA-0.0.32'
  args:
    - ${{ inputs.deploy-env }}
    - ${{ inputs.aws-region }}
    - ${{ inputs.timeout }}
    - ${{ inputs.artifact }}
    - ${{ inputs.version }}
    - ${{ inputs.path }}
